package com.commons.support.db.config;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "CONFIG".
 */
public class Config {

    private Long id;
    /** Not-null value. */
    private String key;
    /** Not-null value. */
    private String value;

    private String columntest="1";
    private String columntest2="2";

    public Config() {
    }

    public Config(Long id) {
        this.id = id;
    }

    public Config(Long id, String key, String value) {
        this.id = id;
        this.key = key;
        this.value = value;
    }

    public Config(String key, String value) {
        this.key = key;
        this.value = value;
    }

    public Config(Long id, String key, String value, String c1, String c2) {
        this.id = id;
        this.key = key;
        this.value = value;
        columntest = c1;
        columntest2 = c2;
    }

    public Config(String key, String value, String c1, String c2) {
        this.key = key;
        this.value = value;
        columntest = c1;
        columntest2 = c2;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getKey() {
        return key;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setKey(String key) {
        this.key = key;
    }

    /** Not-null value. */
    public String getValue() {
        return value;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setValue(String value) {
        this.value = value;
    }

    public String getColumntest() {
        return columntest;
    }

    public void setColumntest(String columntest) {
        this.columntest = columntest;
    }

    public String getColumntest2() {
        return columntest2;
    }

    public void setColumntest2(String columntest2) {
        this.columntest2 = columntest2;
    }
}
